### ISSUE TITLE
6.2.1

### ISSUE THREAD

**Issue by mashirozx** [JeSTeRFLA/FontAwesome-6PRO#2]
any update? there are a lot of new icons after 6.0

**Comment by mashirozx** [comment]
Have fun :) https://github.com/moezhx/font-awesome-pro

**Comment by JeSTeRFLA** [comment]
well, thanks for that. much appreciated

**Comment by JeSTeRFLA** [comment]
https://github.com/JeSTeRFLA/FontAwesome-6FREE-6PRO/releases/tag/FontAwesome6.3

**Comment by mashirozx** [comment]
tks
